# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lenovo/karate-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter karate karatep,$(TARGET_DEVICE)),)

endif
